In [3]:
import numpy as np

# THE ASSIGNMENT STARTS HERE... PLEASE KINDLY UNCOMMENT EACH CELL TO RUN CODES

### HERE, THE SALES.CSV FILE IS OPENED

In [185]:
# file_data = np.genfromtxt("sales.csv", delimiter = ",")
# file_data = file_data.astype("int16")

# data_only = file_data[1:, 1:],
# weeks = data_only[0] 

 

### TO GET THE AVERAGE SALES FOR EACH WEEK

In [184]:
# for _ in weeks:
#     average_sales_weekly = np.average(_)
#     print(average_sales_weekly)
   

### TO GET THE TOTAL SALES FOR THE FIRST MONTH

In [183]:
# first_month = weeks[0:4]
# total_sales_first_month = np.sum(first_month)
# print(total_sales_first_month)

### TO GET THE DAY WITH THE HIGHEST SALES IN THE THIRD MONTH

In [181]:
# third_month = weeks[4:8]

# highest_sales = np.max(third_month)
# if highest_sales in third_month[:,0]:
#     print("The day with the highest sales in the 3rd month is Monday")
# elif highest_sales in third_month[:,1]:
#     print("The day with the highest sales in the 3rd month is Tuesday")
# elif highest_sales in third_month[:,2]:
#     print("The day with the highest sales in the 3rd month is Wednesday")
# elif highest_sales in third_month[:,3]:
#     print("The day with the highest sales in the 3rd month is Thursday")
# elif highest_sales in third_month[:,4]:
#     print("The day with the highest sales in the 3rd month is Friday")
# elif highest_sales in third_month[:,5]:
#     print("The day with the highest sales in the 3rd month is Saturday")
# elif highest_sales in third_month[:,6]:
#     print("The day with the highest sales in the 3rd month is Sunday")

### TO GET THE WEEKS OF THE MONTHS  WITH THE HIGHEST SALES 

In [182]:
# number_of_weeks = 0
# for _ in weeks:
#     number_of_weeks += 1

# number_of_months = "{:.0f}".format(number_of_weeks/4)    #in case number_of_weeks is not a multiple of 4

    
# start = 0
# stop = 4
# count = 0
# for i in range(int(number_of_months) + 1):
#     months = weeks[start:stop]
#     start += 4
#     stop += 4
#     count +=1
    
#     highest_sales = np.max(months)
#     if highest_sales in months[0]:
#         print("The week with the highest sales in month {} is WEEK 1".format(count))
#     elif highest_sales in months[1]:
#         print("The week with the highest sales in month {} is WEEK 2". format(count))
#     elif highest_sales in months[2]:
#         print("The week with the highest sales in month {} is WEEK 3".format(count))
#     elif highest_sales in months[3]:
#         print("The week with the highest sales in month {} is WEEK 4".format(count))



In [4]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
new = np.array([[[4.0,6.0,8.0,5.0],[2.0,5.0,7.0,1.0],[3.0,4.0,6.0,4.0]], [[4.0,6.0,8.0,5.0],[2.0,5.0,7.0,1.0],[3.0,4.0,6.0,4.0]]])
print(new)
new.shape


[[[4. 6. 8. 5.]
  [2. 5. 7. 1.]
  [3. 4. 6. 4.]]

 [[4. 6. 8. 5.]
  [2. 5. 7. 1.]
  [3. 4. 6. 4.]]]


(2, 3, 4)

In [60]:
hey = np.ones((5,5))
# hey = np.ones(shape = (5,5), dtype = "float16")
hey[1:4, 1:4] = [0, 0, 0]
hey[2,2] = 9
print(hey)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [81]:
sunday = np.array([3,5,6,1,8])
np.average(sunday)
np.sum(sunday)

23

In [74]:
yeah = np.array([[3,6,4], [7,8,2], [5,9,3]])
print(yeah)
np.max(yeah, axis = 1)


[[3 6 4]
 [7 8 2]
 [5 9 3]]


array([6, 8, 9])