In [1]:
import numpy as np

# THE ASSIGNMENT STARTS HERE... PLEASE KINDLY UNCOMMENT EACH CELL TO RUN CODES

### HERE, THE SALES.CSV FILE IS OPENED

In [12]:
file_data = np.genfromtxt("sales.csv", delimiter = ",")
file_data = file_data.astype("int16")

data_only = file_data[1:, 1:],
weeks = data_only[0] 

weeks

array([[ 923,  631,  935,  371,  756, 3166,  114],
       [ 918,  626,  930,  366,  751, 3161,  109],
       [ 497,  305,  403,  239,  434,  824,   67],
       [ 499,  307,  405,  241,  436,  826,   69],
       [ 501,  309,  407,  243,  438,  828,   71],
       [ 503,  311,  409,  245,  440,  830,   73],
       [ 505,  313,  411,  247,  442,  832,   75],
       [ 507,  315,  413,  249,  444,  834,   77],
       [ 509,  317,  415,  251,  446,  836,   79],
       [ 511,  319,  417,  253,  448,  838,   81],
       [ 513,  321,  419,  255,  450,  840,   83],
       [ 515,  323,  421,  257,  452,  842,   85],
       [ 517,  325,  423,  259,  454,  844,   87],
       [ 519,  327,  425,  261,  456,  846,   89],
       [ 521,  329,  427,  263,  458,  848,   91],
       [ 523,  331,  429,  265,  460,  850,   93],
       [ 525,  333,  431,  267,  462,  852,   95],
       [ 550,  360,  450,  283,  397, 1200,   30],
       [ 550,  360,  450,  283,  397, 1200,   30],
       [ 550,  360,  450,  283,

### TO GET THE AVERAGE SALES FOR EACH WEEK

In [4]:
for _ in weeks:
    average_sales_weekly = np.average(_)
    print(average_sales_weekly)
   

985.1428571428571
980.1428571428571
395.57142857142856
397.57142857142856
399.57142857142856
401.57142857142856
403.57142857142856
405.57142857142856
407.57142857142856
409.57142857142856
411.57142857142856
413.57142857142856
415.57142857142856
417.57142857142856
419.57142857142856
421.57142857142856
423.57142857142856
467.14285714285717
467.14285714285717
467.14285714285717
467.14285714285717
467.14285714285717
467.14285714285717
467.14285714285717
475.7142857142857
467.14285714285717
458.57142857142856
450.0
441.42857142857144
432.85714285714283
424.2857142857143
415.7142857142857
407.14285714285717
398.57142857142856
390.0
381.42857142857144
374.14285714285717
366.85714285714283
359.57142857142856
352.2857142857143
345.0
337.7142857142857
411.42857142857144
522.7142857142857
690.2857142857143
1011.0
991.5714285714286
972.1428571428571
1032.2857142857142
1013.7142857142857
995.1428571428571
990.1428571428571
985.1428571428571
980.1428571428571
606.8571428571429
601.8571428571429
596.

### TO GET THE TOTAL SALES FOR THE FIRST MONTH

In [5]:
first_month = weeks[0:4]
total_sales_first_month = np.sum(first_month)
print(total_sales_first_month)

19309


### TO GET THE DAY WITH THE HIGHEST SALES IN THE THIRD MONTH

In [9]:
third_month = weeks[4:8]

# highest_sales = np.max(third_month)
# if highest_sales in third_month[:,0]:
#     print("The day with the highest sales in the 3rd month is Monday")
# elif highest_sales in third_month[:,1]:
#     print("The day with the highest sales in the 3rd month is Tuesday")
# elif highest_sales in third_month[:,2]:
#     print("The day with the highest sales in the 3rd month is Wednesday")
# elif highest_sales in third_month[:,3]:
#     print("The day with the highest sales in the 3rd month is Thursday")
# elif highest_sales in third_month[:,4]:
#     print("The day with the highest sales in the 3rd month is Friday")
# elif highest_sales in third_month[:,5]:
#     print("The day with the highest sales in the 3rd month is Saturday")
# elif highest_sales in third_month[:,6]:
#     print("The day with the highest sales in the 3rd month is Sunday")
third_month

array([[501, 309, 407, 243, 438, 828,  71],
       [503, 311, 409, 245, 440, 830,  73],
       [505, 313, 411, 247, 442, 832,  75],
       [507, 315, 413, 249, 444, 834,  77]], dtype=int16)

### TO GET THE WEEKS OF THE MONTHS  WITH THE HIGHEST SALES 

In [6]:
number_of_weeks = 0
for _ in weeks:
    number_of_weeks += 1

number_of_months = "{:.0f}".format(number_of_weeks/4)    #in case number_of_weeks is not a multiple of 4

    
start = 0
stop = 4
count = 0
for i in range(int(number_of_months) + 1):
    months = weeks[start:stop]
    start += 4
    stop += 4
    count +=1
    
    highest_sales = np.max(months)
    if highest_sales in months[0]:
        print("The week with the highest sales in month {} is WEEK 1".format(count))
    elif highest_sales in months[1]:
        print("The week with the highest sales in month {} is WEEK 2". format(count))
    elif highest_sales in months[2]:
        print("The week with the highest sales in month {} is WEEK 3".format(count))
    elif highest_sales in months[3]:
        print("The week with the highest sales in month {} is WEEK 4".format(count))



The week with the highest sales in month 1 is WEEK 1
The week with the highest sales in month 2 is WEEK 4
The week with the highest sales in month 3 is WEEK 4
The week with the highest sales in month 4 is WEEK 4
The week with the highest sales in month 5 is WEEK 2
The week with the highest sales in month 6 is WEEK 1
The week with the highest sales in month 7 is WEEK 1
The week with the highest sales in month 8 is WEEK 1
The week with the highest sales in month 9 is WEEK 1
The week with the highest sales in month 10 is WEEK 1
The week with the highest sales in month 11 is WEEK 1
The week with the highest sales in month 12 is WEEK 2
The week with the highest sales in month 13 is WEEK 1
The week with the highest sales in month 14 is WEEK 1
The week with the highest sales in month 15 is WEEK 1
The week with the highest sales in month 16 is WEEK 1
The week with the highest sales in month 17 is WEEK 4
The week with the highest sales in month 18 is WEEK 4
The week with the highest sales in mo

In [4]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
new = np.array([[[4.0,6.0,8.0,5.0],[2.0,5.0,7.0,1.0],[3.0,4.0,6.0,4.0]], [[4.0,6.0,8.0,5.0],[2.0,5.0,7.0,1.0],[3.0,4.0,6.0,4.0]]])
print(new)
new.shape


[[[4. 6. 8. 5.]
  [2. 5. 7. 1.]
  [3. 4. 6. 4.]]

 [[4. 6. 8. 5.]
  [2. 5. 7. 1.]
  [3. 4. 6. 4.]]]


(2, 3, 4)

In [60]:
hey = np.ones((5,5))
# hey = np.ones(shape = (5,5), dtype = "float16")
hey[1:4, 1:4] = [0, 0, 0]
hey[2,2] = 9
print(hey)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [81]:
sunday = np.array([3,5,6,1,8])
np.average(sunday)
np.sum(sunday)

23

In [74]:
yeah = np.array([[3,6,4], [7,8,2], [5,9,3]])
print(yeah)
np.max(yeah, axis = 1)


[[3 6 4]
 [7 8 2]
 [5 9 3]]


array([6, 8, 9])