In [1]:
import numpy as np

In [2]:
mat = np.array([1, 2, 3])

In [109]:
mat = np.array([1])
mat = list(mat)
x = 0
while x < 30 and mat[-1] !=7:
    
    randnum = np.random.randint(1,10)
    
    mat.append(randnum)
    x +=1
mat = np.array(mat)
(mat)

array([1, 3, 7])

In [47]:
np.matrix(mat).mean()

4.239130434782608

In [131]:
a = np.array([ 8.,3.,10.,8.,2.,2.,10.,10.,5.,10.,2.,10.,9.,10.,9.,4.,2.,8.,7.,4.,1.,4.,5.,6.,6.])

In [133]:
a = a.reshape(5,5)

In [134]:
a.shape

(5, 5)

In [137]:
for item in a.flat:
    print(item)
    if item == 8.0:
        print("hurray")

8.0
hurray
3.0
10.0
8.0
hurray
2.0
2.0
10.0
10.0
5.0
10.0
2.0
10.0
9.0
10.0
9.0
4.0
2.0
8.0
hurray
7.0
4.0
1.0
4.0
5.0
6.0
6.0


In [138]:
A = np.matrix([1,2,3,4,5,6,7,8,9], dtype="float")
x = np.matrix([1,2,3])
B = np.matrix([-0.1, -0.2, -0.3, 3, 10, 2, 4, 2, 0.5])

In [140]:
A.shape = (3,3)
B.shape = (3,3)

In [141]:
A * B

matrix([[17.9, 25.8,  5.2],
        [38.6, 61.2, 11.8],
        [59.3, 96.6, 18.4]])

In [142]:
A.dot(B)

matrix([[17.9, 25.8,  5.2],
        [38.6, 61.2, 11.8],
        [59.3, 96.6, 18.4]])

In [144]:
np.cross(A,B)

array([[ 1.11022302e-16, -5.55111512e-17,  0.00000000e+00],
       [-5.00000000e+01,  1.00000000e+01,  2.50000000e+01],
       [-1.40000000e+01,  3.25000000e+01, -1.80000000e+01]])